name: Android Appium Tests

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  appium-test:
    runs-on: macos-13  # Intel tabanlı emülatör performansı için ideal

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Appium & Driver
        run: |
          npm install -g appium
          appium driver install uiautomator2

      - name: Run Android Emulator and Tests
        uses: ReactiveCircus/android-emulator-runner@v2
        with:
          api-level: 30
          target: google_apis
          arch: x86_64
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          script: |
            appium --log appium.log & 
            mvn clean test
