name: Android Test Automation

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # APK DOWNLOAD
      - name: Download APK from Release
        run: |
          curl -L -o app.apk https://github.com/ErgunYilmaz/TatilbudurMobilTestAutomationProject/releases/download/apk-v1/tb.apk

      # JAVA
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      # ANDROID + EMULATOR (FAST)
      - name: Start Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          arch: x86_64
          profile: Nexus 6
          emulator-options: >
            -no-window
            -no-audio
            -no-boot-anim
            -gpu swiftshader_indirect
          script: |
            adb wait-for-device
            adb install app.apk
            mvn clean test

      # ALLURE REPORT
      - name: Generate Allure Report
        run: mvn allure:report

      # VIDEO HTML
      - name: Prepare Video Page
        run: |
          mkdir -p public
          cp -r target/allure-report/* public/
          
          echo "<html><body><h2>Test Video</h2><video width='800' controls><source src='video.mp4' type='video/mp4'></video></body></html>" > public/video.html
          
          if [ -f target/*.mp4 ]; then
            cp target/*.mp4 public/video.mp4
          fi

      # GITHUB PAGES
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public

      # MAIL
      - name: Send Email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "Test Raporu"
          to: |
            ergun.yilmaz@tatilbudur.com,
            letafet.erol@tatilbudur.com,
            erhan.isler@tatiludur.com,
            bahar.yildiz@tatilbudur.com,            
            hüseyin.eraslan@tatilbudur.com
          from: "Test Automation"
          body: |
            Test tamamlandı.

            Rapor:
            https://ergunyilmaz.github.io/TatilbudurMobilTestAutomationProject/

            Video:
            https://ergunyilmaz.github.io/TatilbudurMobilTestAutomationProject/video.html
